### ISSUE TITLE
Update to version 3 of the docusign_esign gem

### ISSUE THREAD

**Issue by abuisman** [docusign/qs-ruby#6]
The current examples use the old 1.x version of the docusign_esign gem, but since version 2 the API has changed.

Please update the examples.

**Comment by LarryKlugerDS** [comment]
Thank you for the report. I have filed a bug report with the examples team.

**Comment by abuisman** [comment]
@LarryKlugerDS Can you guys please look at this again?

**Comment by LarryKlugerDS** [comment]
Hi @abuisman ,
I'm told that this issue was fixed.
Have you tried it recently? 
Thank you,
Larry
